
baseURL = 'https://fuzzynum.github.io'
languageCode = 'en-us'
title = "Luke Howard"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'